---
- name: Setup HAProxy Blue-Green Load Balancer
  hosts: loadbalancer
  become: yes
  vars:
    # These are your fixed VM IPs
    blue_ip: "10.18.168.80"
    green_ip: "10.18.168.79"
    
    # 'active_color' is the placeholder that AWX will fill
    # It defaults to blue if nothing is sent
    active_color: "{{ deployment_color | default('blue') }}"

  tasks:
    - name: Set target IP based on color
      set_fact:
        target_vm_ip: "{{ blue_ip if active_color == 'blue' else green_ip }}"
        staging_vm_ip: "{{ green_ip if active_color == 'blue' else blue_ip }}"

    - name: Deploy HAProxy Configuration
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        block: |
          frontend http_in
              bind *:80
              acl is_staging hdr(host) -i ansiblestaging.com
              
              use_backend staging_pool if is_staging
              default_backend production_pool

          backend production_pool
              # Points to the 'active' color chosen in AWX
              server prod_node {{ target_vm_ip }}:80 check

          backend staging_pool
              # Points to the 'standby' color for testing
              server stage_node {{ staging_vm_ip }}:80 check
      notify: restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
