- name: Restore AWX 3 on Port 80
      copy:
        content: |
          server {
              listen 80;
              root /var/www/html;
              index index.html;
          }
        dest: /etc/nginx/sites-enabled/awx3

    - name: Ensure AWX 3 Content exists
      copy:
        content: "<h1>Welcome to AWX 3</h1>"
        dest: /var/www/html/index.html

    - name: Keep AWX 2 on Port 8081
      copy:
        content: |
          server {
              listen 8081;
              root /var/www/awx2;
              index index.html;
          }
        dest: /etc/nginx/sites-enabled/awx2
      notify: restart nginx
